package com.goldsprite.gdxgradle

import org.gradle.api.Project

/**
 * Git commit-msg 钩子自动安装器
 * 在 Gradle 配置阶段立即写入钩子, 强制规范提交格式
 */
class GitHookInstaller {

    static void install(Project project, GdxTasksExtension ext) {
        // 如果当前是被 includeBuild 引入的 composite 子构建，跳过 hook 安装
        // 避免构建宿主项目时越权修改被包含库项目的 git hook
        if (project.gradle.parent != null) {
            return
        }

        def rootDir = project.rootProject.rootDir
        def gitHooksDir = new File(rootDir, '.git/hooks')

        // 安全检查: 只有在 Git 仓库时才执行
        if (!gitHooksDir.exists()) return

        def hookFile = new File(gitHooksDir, 'commit-msg')
        def types = ext.commitTypes.get().join('|')
        def typesHelp = ext.commitTypes.get().collect { "echo \"✅ ${it}\"" }.join("\n    ")
        def projectName = project.rootProject.name

        def rawContent = """#!/bin/sh
# ------------------------------------------------------------------
# Auto-generated by ${projectName} GdxGradle Plugin. Do not edit manually.
# ------------------------------------------------------------------

commit_msg_file=\$1
commit_msg=\$(cat "\$commit_msg_file")

# 正则: 必须以指定类型开头
# 格式: type: summary 或 type(scope): summary
pattern="^(${types})(\\\\(.+\\\\))?: .+\$"

if ! echo "\$commit_msg" | grep -qE "\$pattern"; then
    echo "❌ [COMMIT REJECTED] 提交格式校验失败！"
    echo "-----------------------------------------------------------------------"
    echo "格式要求: <type>: <summary>"
    echo "          (空行)"
    echo "          <details body...>"
    echo "-----------------------------------------------------------------------"
    ${typesHelp}
    echo "-----------------------------------------------------------------------"
    echo "示例标题: feat: 增加Web浏览器组件"
    echo "-----------------------------------------------------------------------"
    exit 1
fi
"""

        try {
            // 强制 Unix 换行符, 防止 Windows CRLF 导致 Shell 脚本报错
            String unixContent = rawContent.replaceAll("\\r\\n?", "\n")
            hookFile.setBytes(unixContent.getBytes("UTF-8"))
            hookFile.setExecutable(true)
            println "✅ Git Commit Hook (commit-msg) 已更新 (规则: ${types})。"
        } catch (Exception ignored) {
            // 忽略异常, 防止非 Git 环境报错
        }
    }
}
