package com.goldsprite.gdxgradle

import org.gradle.api.Project

/**
 * Git commit-msg 钩子自动安装器
 * 在 Gradle 配置阶段立即写入钩子, 强制规范提交格式
 */
class GitHookInstaller {

	static void install(Project project, GdxTasksExtension ext) {
		// 如果当前是被 includeBuild 引入的 composite 子构建，跳过 hook 安装
		// 避免构建宿主项目时越权修改被包含库项目的 git hook
		if (project.gradle.parent != null) {
			return
		}

		def rootDir = project.rootProject.rootDir
		def gitHooksDir = new File(rootDir, '.git/hooks')

		// 安全检查: 只有在 Git 仓库时才执行
		if (!gitHooksDir.exists()) return

		def hookFile = new File(gitHooksDir, 'commit-msg')
		def projectName = project.rootProject.name

		// 构建类型校验正则
		def (typePattern, helpText) = buildTypePatternAndHelp(ext)

		// 构建跳过模式
		def skipPatterns = buildSkipPatterns(ext)

		def rawContent = """#!/bin/sh
# ------------------------------------------------------------------
# Auto-generated by ${projectName} GdxGradle Plugin. Do not edit manually.
# ------------------------------------------------------------------

commit_msg_file=\$1
commit_msg=\$(cat "\$commit_msg_file")

# ============================================================
# 检查是否需要跳过校验（Git 自动生成的特殊提交）
# ============================================================
${skipPatterns}

# ============================================================
# 校验提交格式
# ============================================================
pattern="${typePattern}"

if ! echo "\$commit_msg" | grep -qE "\$pattern"; then
    echo "❌ [COMMIT REJECTED] 提交格式校验失败！"
    echo "-----------------------------------------------------------------------"
    echo "格式要求: <type>: <summary>"
    echo "          (空行)"
    echo "          <details body...>"
    echo "-----------------------------------------------------------------------"
${helpText}
    echo "-----------------------------------------------------------------------"
    echo "示例标题: feat: 增加Web浏览器组件"
    echo "          fix: 修复碰撞检测空指针异常"
    echo "-----------------------------------------------------------------------"
    exit 1
fi
"""

		try {
			// 强制 Unix 换行符, 防止 Windows CRLF 导致 Shell 脚本报错
			String unixContent = rawContent.replaceAll("\\r\\n?", "\n")
			hookFile.setBytes(unixContent.getBytes("UTF-8"))
			hookFile.setExecutable(true)
			println "✅ Git Commit Hook (commit-msg) 已更新。"
		} catch (Exception ignored) {
			// 忽略异常, 防止非 Git 环境报错
		}
	}

	/**
	 * 构建类型校验正则和帮助文本
	 */
	private static List buildTypePatternAndHelp(GdxTasksExtension ext) {
		def useDetailed = ext.useDetailedCommitTypes.getOrElse(false)
		def typeDefs = ext.commitTypeDefs.getOrElse([])

		if (useDetailed && !typeDefs.isEmpty()) {
			// 使用详细的类型定义
			def types = typeDefs.collect { it.type }.join('|')
			def pattern = "^(${types})(\\\\(.+\\\\))?: .+\$"
			def helpText = typeDefs.collect { ct ->
				"    echo \"✅ ${ct.type.padRight(10)} - ${ct.description}\""
			}.join('\n')
			return [pattern, helpText]
		}

		// 使用简单的字符串列表（向后兼容）
		def types = ext.commitTypes.get()
		def pattern = "^(${types.join('|')})(\\\\(.+\\\\))?: .+\$"
		def helpText = types.collect { t ->
			"    echo \"✅ ${t}\""
		}.join('\n')
		return [pattern, helpText]
	}

	/**
	 * 构建跳过校验的 shell 代码
	 */
	private static String buildSkipPatterns(GdxTasksExtension ext) {
		def patterns = []

		// 添加默认跳过模式
		if (ext.enableDefaultSkipPatterns.getOrElse(true)) {
			patterns.addAll(CommitType.defaultSkipPatterns())
		}

		// 添加用户自定义跳过模式
		if (ext.skipPatterns.isPresent()) {
			patterns.addAll(ext.skipPatterns.get())
		}

		if (patterns.isEmpty()) {
			return "# 无跳过模式配置"
		}

		// 构建 shell 检查代码
		def sb = new StringBuilder()
		sb.append("# 自动跳过模式（Merge、Revert等特殊提交）\n")
		patterns.each { pattern ->
			// 对单引号进行转义处理，避免 shell 语法错误
			def escapedPattern = pattern.replace("'", "'\"'\"'")
			sb.append("if echo \"\$commit_msg\" | grep -qE '${escapedPattern}'; then\n")
			sb.append("    exit 0\n")
			sb.append("fi\n")
		}

		return sb.toString()
	}
}
